export default {
  error404: "/not-found",
  home: "/",
  tradingCards: "/trading-cards",
  cardMatch: "/card-match",
  explore: "/explore",
  enter: "/enter",
  pokemonBattle: "/pokemon-battle",
  pokemonQuest: "/pokemon-quest",
  whosThatPokemon: "/whos-that-pokemon",
  pokedex: "/pokedex",
  homeImages: [
    "pokemon18.jpg",
    "pika.jpg",
    "misty_staryu.png",
    "pokemon15.png",
    "bulb-pika.jpg",
    "nurse-joy.png",
    "pokemon38.jpg",
    "pokemon16.png",
    "mr-mime.png",
    "pokemon2.jpg",
    "pokemon26.png",
    "pokemon30.png",
    "pokemon13.jpg",
    "pokemon19.jpg",
    "pokemon17.png",
    "pokemon7.jpg",
    "pokemon8.jpg",
    "pokemon14.png",
    "pokemon28.jpg",
    "pokemon34.jpg",
    "rhydon.png",
    "pokemon25.jpg",
    "pokemon33.jpg",
    "pokemon11.jpg",
    "zapdos.jpg",
    "alakazam.png",
    "cloyster.png",
    "gyrados-img.jpg",
    "koffin.png",
    "machamp.png",
    "onix.jpeg",
    "pokemon_ash_gengar.jpg",
    "pokemon37.png",
    "pokemon31.jpg",
    "pokemon_bulbasaur_battle.jpg",
    "pokemon_oddish_cute.jpg",
    "pokemon1.png",
    "pokemon3.png",
    "pokemon5.png",
    "pokemon6.jpg",
    "pokemon9.jpg",
    "pokemon10.jpg",
    "pokemon12.jpg",
    "pokemon20.png",
    "pokemon21.png",
    "pokemon23.jpg",
    "pokemon24.png",
    "pokemon27.png",
    "pokemon29.jpg",
    "pokemon36.jpg",
    "gyrados.jpg",
    "vileplume.jpg",
  ],
};
