export const pokemonList = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran-f",
  "Nidorina",
  "Nidoqueen",
  "Nidoran-m",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr.Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
];

export const pokemonListDescription = [
  "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.",
  "The bulb on its back grows by drawing energy. It gives off an aroma when it is ready to bloom.",
  "By spreading the broad petals of its flower and catching the sun’s rays, it fills its body with power.",
  "If it’s healthy, the flame on the tip of its tail will burn vigorously, even if it gets a bit wet.",
  "In the rocky mountains where Charmeleon live, their fiery tails shine at night like stars.",
  "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
  "It shelters itself in its shell, then strikes back with spouts of water at every opportunity.",
  "It cleverly controls its furry ears and tail to maintain its balance while swimming.",
  "Once it takes aim at its enemy, it blasts out water with even more force than a fire hose.",
  "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
  "A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution.",
  "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
  "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
  "While awaiting evolution, it hides from predators under leaves and in nooks of branches.",
  "It can take down any opponent with its powerful poison stingers. It sometimes attacks in swarms.",
  "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
  "It flies over its wide territory in search of prey, downing it with its highly developed claws.",
  "It spreads its beautiful wings wide to frighten its enemies. It can fly at Mach 2 speed.",
  "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
  "It whittles its constantly growing fangs by gnawing on hard things. It can chew apart cinder walls.",
  "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.",
  "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
  "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.",
  "The pattern on its belly is for intimidation. It constricts foes while they are frozen in fear.",
  "It has small electric sacs on both its cheeks. If threatened, it looses electric charges from the sacs.",
  "When electricity builds up inside its body, it becomes feisty. It also glows in the dark.",
  "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
  "It is skilled at slashing enemies with its claws. If broken, they start to grow back in a day.",
  "The poison hidden in its small horn is extremely potent. Even a tiny scratch can have fatal results.",
  "The female’s horn develops slowly. Prefers physical attacks such as clawing and biting.",
  "Its entire body is armored with hard scales. It will protect the young in its burrow with its life.",
  "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
  "It has a violent disposition and stabs foes with its horn, which oozes poison upon impact.",
  "One swing of its mighty tail can snap a telephone pole as if it were a matchstick.",
  "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.",
  "It is very wary and rarely shows itself to people. Its ears can hear a pin drop over half a mile away.",
  "As it develops, its single white tail gains color and splits into six. It is quite warm and cuddly.",
  "It has nine long tails and fur that gleams gold. It is said to live for 1,000 years.",
  "Uses its alluring eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep.",
  "Their fur feels so good that if two of them snuggle together, they won’t want to be separated.",
  "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
  "Once it starts sucking blood, it does not stop until it is full. It flies at night in search of prey.",
  "During the day, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight.",
  "The honey it drools from its mouth smells so atrocious, it can curl noses more than a mile away.",
  "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.",
  "As its body grows large, oriental mushrooms named tochukaso start sprouting out of its back.",
  "The larger the mushroom on its back grows, the stronger the mushroom spores it scatters.",
  "Its eyes also function as radar units. It catches and eats small bugs that hide in darkness.",
  "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.",
  "Lives about one yard underground where it feeds on plant roots. It sometimes appears aboveground.",
  "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
  "It loves anything that shines. It especially adores coins that it picks up and secretly hoards.",
  "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
  "It never remembers using its odd powers, so it always tilts its head in puzzlement.",
  "It appears by waterways at dusk. It may use telekinetic powers if its forehead glows mysteriously.",
  "It lives in treetop colonies. If one becomes enraged, the whole colony rampages for no reason.",
  "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
  "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.",
  "A Pokémon that has long been admired for its beauty. It runs agilely as if on wings.",
  "Its newly grown legs prevent it from walking well. It appears to prefer swimming over walking.",
  "The swirl on its belly subtly undulates. Staring at it may gradually cause drowsiness.",
  "This strong and skilled swimmer is even capable of crossing the Pacific Ocean just by kicking.",
  "Sleeps 18 hours a day. If it senses danger, it will teleport itself to safety even as it sleeps.",
  //  above abra#63 next kadabra #64
];
