export const pokemonList = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran-f",
  "Nidorina",
  "Nidoqueen",
  "Nidoran-m",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr.Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
];

export const pokemonListDescription = [
  "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKÉMON.",
  "The bulb on its back grows by drawing energy. It gives off an aroma when it is ready to bloom.",
  "By spreading the broad petals of its flower and catching the sun’s rays, it fills its body with power.",
  "If it’s healthy, the flame on the tip of its tail will burn vigorously, even if it gets a bit wet.",
  "In the rocky mountains where Charmeleon live, their fiery tails shine at night like stars.",
  "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
  "It shelters itself in its shell, then strikes back with spouts of water at every opportunity.",
  "It cleverly controls its furry ears and tail to maintain its balance while swimming.",
  "Once it takes aim at its enemy, it blasts out water with even more force than a fire hose.",
  "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
  "A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution.",
  "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
  "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
  "While awaiting evolution, it hides from predators under leaves and in nooks of branches.",
  "It can take down any opponent with its powerful poison stingers. It sometimes attacks in swarms.",
  "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
  "It flies over its wide territory in search of prey, downing it with its highly developed claws.",
  "It spreads its beautiful wings wide to frighten its enemies. It can fly at Mach 2 speed.",
  "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
  "It whittles its constantly growing fangs by gnawing on hard things. It can chew apart cinder walls.",
  "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.",
  "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
  "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.",
  "The pattern on its belly is for intimidation. It constricts foes while they are frozen in fear.",
  "It has small electric sacs on both its cheeks. If threatened, it looses electric charges from the sacs.",
  "When electricity builds up inside its body, it becomes feisty. It also glows in the dark.",
  "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
  "It is skilled at slashing enemies with its claws. If broken, they start to grow back in a day.",
  "The poison hidden in its small horn is extremely potent. Even a tiny scratch can have fatal results.",
  "The female’s horn develops slowly. Prefers physical attacks such as clawing and biting.",
  "Its entire body is armored with hard scales. It will protect the young in its burrow with its life.",
  "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
  "It has a violent disposition and stabs foes with its horn, which oozes poison upon impact.",
  "One swing of its mighty tail can snap a telephone pole as if it were a matchstick.",
  "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.",
  "It is very wary and rarely shows itself to people. Its ears can hear a pin drop over half a mile away.",
  "As it develops, its single white tail gains color and splits into six. It is quite warm and cuddly.",
  "It has nine long tails and fur that gleams gold. It is said to live for 1,000 years.",
  "Uses its alluring eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep.",
  "Their fur feels so good that if two of them snuggle together, they won’t want to be separated.",
  "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
  "Once it starts sucking blood, it does not stop until it is full. It flies at night in search of prey.",
  "During the day, it stays in the cold underground to avoid the sun. It grows by bathing in moonlight.",
  "The honey it drools from its mouth smells so atrocious, it can curl noses more than a mile away.",
  "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.",
  "As its body grows large, oriental mushrooms named tochukaso start sprouting out of its back.",
  "The larger the mushroom on its back grows, the stronger the mushroom spores it scatters.",
  "Its eyes also function as radar units. It catches and eats small bugs that hide in darkness.",
  "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.",
  "Lives about one yard underground where it feeds on plant roots. It sometimes appears aboveground.",
  "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
  "It loves anything that shines. It especially adores coins that it picks up and secretly hoards.",
  "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
  "It never remembers using its odd powers, so it always tilts its head in puzzlement.",
  "It appears by waterways at dusk. It may use telekinetic powers if its forehead glows mysteriously.",
  "It lives in treetop colonies. If one becomes enraged, the whole colony rampages for no reason.",
  "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
  "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.",
  "A PokÉmon that has long been admired for its beauty. It runs agilely as if on wings.",
  "Its newly grown legs prevent it from walking well. It appears to prefer swimming over walking.",
  "The swirl on its belly subtly undulates. Staring at it may gradually cause drowsiness.",
  "This strong and skilled swimmer is even capable of crossing the Pacific Ocean just by kicking.",
  "Sleeps 18 hours a day. If it senses danger, it will teleport itself to safety even as it sleeps.",
  "If it uses its abilities, it emits special alpha waves that cause machines to malfunction.",
  "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.",
  "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
  "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.",
  "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.",
  "A carnivorous POKÉMON that traps and eats bugs. It uses its root feet to soak up needed moisture.",
  "The leafy parts act as cutters for slashing foes. It spits a fluid that dissolves everything.",
  "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
  "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.",
  "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
  "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
  "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
  "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.",
  "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.",
  "Very competitive, this POKÉMON will chase anything that moves fast in the hopes of racing it.",
  "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.",
  "The SHELLDER that is latched onto SLOWPOKE’s tail is said to feed on the host’s left over scraps.",
  "It is born with the ability to defy gravity. It floats in air on powerful electromagnetic waves.",
  "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.",
  "The sprig of green onions it holds is its weapon. It is used much like a metal sword.",
  "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.",
  "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.",
  "The protruding horn on its head is very hard. It is used for bashing through thick ice.",
  "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.",
  "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.",
  "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.",
  "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.",
  "When attacked, it launches its horns in quick volleys. Its innards have never been seen.",
  "Almost invisible, this gaseous POKÉMON cloaks the target and puts it to sleep without notice.",
  "Because of its ability to slip through block walls, it is said to be from another dimension.",
  "Under a full moon, this POKÉMON likes to mimic the shadows of people and laugh at their fright.",
  "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.",
  "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.",
  "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.",
  "Its pincers are not only powerful weapons, they are used for balance when walking sideways.",
  "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.",
  "Usually found in power plants. Easily mistaken for a POKÉ BALL, they have zapped many people.",
  "It stores electric energy under very high pressure. It often explodes with little or no provocation.",
  "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.",
  "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.",
  "Because it never removes its skull helmet, no one has ever seen this POKÉMON’s real face.",
  "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.",
  "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.",
  "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.",
  "Its tongue can be extended like a chameleon’s. It leaves a tingling sensation when it licks enemies.",
  "In hot places, its internal gases could expand and explode without any warning. Be very careful!",
  "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.",
  "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.",
  "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.",
  "A rare and elusive POKÉMON that is said to bring happiness to those who manage to get it.",
  "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.",
  "The infant rarely ventures out of its mother’s protective pouch until it is 3 years old.",
  "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.",
  "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.",
  "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.",
  "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.",
  "An enigmatic POKÉMON that can effortlessly regenerate any appendage it loses in battle.",
  "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.",
  "If interrupted while it is miming, it will slap around the offender with its broad hands.",
  "With ninja-like agility and speed, it can create the illusion that there is more than one.",
  "It has several different cry patterns, each of which seems to have its own meaning.",
  "Normally found near power plants, they can wander away and cause major blackouts in cities.",
  "Its body always burns with an orange glow that enables it to hide perfectly among flames.",
  "Grips its prey in its pincers and squeezes hard! It can’t move if it’s cold, so it lives in warm places.",
  "When it targets an enemy, it charges furiously while whipping its body with its long tails.",
  "Famous for being very unreliable. It can be found swimming in seas, lakes, rivers and shallow puddles.",
  "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.",
  "A POKÉMON that has been overhunted almost to extinction. It can ferry people across the water.",
  "When it spots an enemy, its body transfigures into an almost perfect copy of its opponent.",
  "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.",
  "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid’s.",
  "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.",
  "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.",
  "A POKÉMON that consists entirely of programming code. Capable of moving freely in cyberspace.",
  "Although long extinct, in rare cases, it can be genetically resurrected from fossils.",
  "A prehistoric POKÉMON that died out when its heavy shell made it impossible to catch prey.",
  "A POKÉMON that was resurrected from a fossil found in what was once the ocean floor eons ago.",
  "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.",
  "A ferocious, prehistoric POKÉMON that goes for the enemy’s throat with its serrated saw-like fangs.",
  "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
  "A legendary bird POKÉMON that is said to appear to doomed people who are lost in icy mountains.",
  "A legendary bird POKÉMON that is said to appear from clouds while dropping enormous lightning bolts.",
  "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.",
  "The existence of this mythical POKÉMON was only recently confirmed by a fisherman who caught one.",
  "A mystical POKÉMON that exudes a gentle aura. Has the ability to change climate conditions.",
  "An extremely rarely seen marine POKÉMON. Its intelligence is said to match that of humans.",
  "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
];
